spring.config.import=optional:file:.env[.properties]
spring.application.name=iti

#SQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Logging
spring.jpa.show-sql=true
logging.level.org.springframework.security=trace
logging.level.org.hibernate.jdbc.bind=trace


#JWT
jwt.access-token.expiration=86400000
jwt.refresh-token.expiration=604800000
jwt.key=${JWT_KEY}