package com.almahir.iti.controller;

import com.almahir.iti.dto.request.CreateIntentionRequest;
import com.almahir.iti.dto.response.CreateIntentionResponse;
import com.almahir.iti.dto.response.PaymentStatusResponse;
import com.almahir.iti.model.AuthUser;
import com.almahir.iti.service.PaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/payment")
@RequiredArgsConstructor
@Slf4j
@Tag(
        name = "Payments",
        description = """
                Payment operations using Paymob.
                
                FLOW:
                1) Create a payment intention using POST /api/payment/intentions.
                2) Backend creates the Paymob intention and returns the clientSecret + publicKey.
                3) Mobile app passes these values to the Paymob SDK to complete payment.
                4) Paymob sends the final payment result to the webhook endpoint.
                5) Backend updates the payment transaction and activates the subscription
                   only after a successful webhook.
                
                The client must NOT send the Paymob secret key.
                """
)
public class PaymentController {

    private final PaymentService paymentService;

    @Operation(
            summary = "Create Payment Intention",
            description = """
                    Creates a new Paymob payment intention for the authenticated user.
                    
                    The packageId field currently expects the package CODE
                    (for example: pkg-light), not the UUID.
                    
                    The idempotencyKey should be generated by the client for each
                    logical payment attempt. Reusing the same key allows the backend
                    to reuse an existing valid pending intention.
                    
                    On success, the response contains:
                    - clientSecret: pass this to the Paymob SDK.
                    - publicKey: Paymob public key required by the SDK.
                    - intentionId: backend/Paymob reference used to check payment status.
                    """
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("isAuthenticated()")
    @PostMapping("/intentions")
    public ResponseEntity<CreateIntentionResponse> createIntention(
            @AuthenticationPrincipal AuthUser authUser,
            @RequestBody CreateIntentionRequest request
    ) {
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(paymentService.createIntention(authUser.getUser(), request));
    }

    @Operation(
            summary = "Get Payment Status",
            description = """
                    Retrieves the current payment status for a payment intention.
                    
                    The intention must belong to the authenticated user.
                    
                    Possible statuses include:
                    - PENDING
                    - SUCCESS
                    - FAILED
                    """
    )
    @SecurityRequirement(name = "bearerAuth")
    @PreAuthorize("isAuthenticated()")
    @GetMapping("/intentions/{id}/status")
    public ResponseEntity<PaymentStatusResponse> getStatus(
            @AuthenticationPrincipal AuthUser authUser,
            @Parameter(
                    description = "Paymob intention/reference ID returned when creating the payment intention",
                    required = true
            )
            @PathVariable("id") String intentionId
    ) {
        return ResponseEntity.ok(
                paymentService.getStatus(authUser.getUser(), intentionId)
        );
    }

    @Operation(
            summary = "Paymob Payment Webhook",
            description = """
                    Receives payment status notifications from Paymob.
                    
                    This endpoint is called by Paymob and must NOT require the user's JWT.
                    The backend validates the Paymob HMAC signature before processing
                    the webhook.
                    
                    A successful webhook changes the transaction to SUCCESS and
                    activates the user's subscription.
                    
                    Do not call this endpoint manually from the mobile application.
                    """
    )
    @PostMapping("/webhooks/paymob")
    public ResponseEntity<Void> handleWebhook(
            @RequestBody Map<String, Object> payload,
            @Parameter(
                    description = "Paymob HMAC signature used to verify webhook authenticity",
                    required = false
            )
            @RequestParam(required = false) String hmac
    ) {
        paymentService.handlePaymobWebhook(payload, hmac);
        return ResponseEntity.ok().build();
    }
}